#! /bin/bash
section=$1
user=$USER
path=$(pwd)


controllers='controllers'
models='models'
views='views'

if [ -z $section ]; then
    echo "Please provide a section name"
    exit 1
fi

# Creare controller.
contr=$controllers/$section.php
model="${section}s"
view=$views/$section

touch $contr
chmod 0775 $contr
chown $USER $contr
echo "<?php" >> $contr
echo "class $section extends $model" >> $contr
echo "{" >> $contr
echo "    public function __construct() {" >> $contr
echo "        parent::__construct();" >> $contr
echo "    }" >> $contr
echo "" >> $contr
echo "    public function index()" >> $contr
echo "    {" >> $contr
echo "        // Code example." >> $contr
echo "        $this->data['message'] = '<div class="alert alert-success" role="alert">UNDER CONSTRUCTION</br>" >> $contr
echo "        <a href="/?c=Home">Link back</a>" >> $contr
echo "        </div>';" >> $contr
echo "    }" >> $contr
echo "}" >> $contr

#Create model
mp=$models/$model.php
touch $mp
chown $USER $mp
chmod 0775 $mp
echo "<?php" >> $mp
echo "class $model extends Lib" >> $mp
echo "{" >> $mp
echo "    public function __construct()" >> $mp
echo "    {" >> $models/$model.php
echo "        parent::__construct();" >> $mp
echo "    }" >> $mp
echo "}" >> $mp

#Create view directory and file
mkdir $view
chown $USER $view
chmod 0776 $view

#create index.php file
touch $view/index.php
chown $USER $view/index.php
chmod 0776 $view/index.php
echo "            <div class="text-left">" >> $view/$section.php
echo "                 <h5>Autogenerated section sceleton: $section</h5>" >> $view/$section.php
echo "                 <p class="font-weight-light text-info">Open the files and write your code.</p>" >> $view/$section.php
echo "            </div>" >> $view/$section.php
echo "            <div class="text-center">" >> $view/$section.php
echo "                                  <?php " >> $view/$section.php
echo "                   echo $class->data['message'];" >> $view/$section.php
echo "?>" >> $view/$section.php
echo "            </div>'" >> $view/$section.php
